name = "DiBitVectors"
uuid = "b332d270-17d7-4a15-8ba9-1b15059bf12d"
authors = ["Seth Bromberger <github@bromberger.com>"]
version = "0.1.0"

[deps]
BitOperations = "e1e0eea2-bc69-5bf6-8574-13634873a17c"